"""empty message

Revision ID: 3dad44889eab
Revises: 
Create Date: 2019-12-06 22:19:55.677359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dad44889eab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alimentos', sa.Column('fornecedor', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'alimentos', ['fornecedor'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alimentos', type_='unique')
    op.drop_column('alimentos', 'fornecedor')
    # ### end Alembic commands ###
