"""empty message

Revision ID: 7928a9056147
Revises: 
Create Date: 2019-12-06 21:29:19.441595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7928a9056147'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alimentos', sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('alimentos', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alimentos', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('alimentos', '_id')
    # ### end Alembic commands ###
